### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by remyleone** [github/contributors#39]
It seems that there is no check on the sponsor info variable

```
$ ORGANIZATION=scaleway REPOSITORY=scaleway-cli GH_TOKEN=$GITHUB_COM_TOKEN python3 ./contributors.py
Traceback (most recent call last):
  File "/Users/rleone/workspace/contributors/./contributors.py", line 176, in <module>
    main()
  File "/Users/rleone/workspace/contributors/./contributors.py", line 24, in main
    ) = env.get_env_vars()
        ^^^^^^^^^^^^^^^^^^
  File "/Users/rleone/workspace/contributors/env.py", line 56, in get_env_vars
    sponsor_info = sponsor_info.lower().strip()
                   ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by zkoppert** [comment]
fixed via 4a1d3ce
